apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 16.0.0
    helm:
      releaseName: rabbitmq
      values: |
        replicaCount: 3
        clustering:
          enabled: true

        auth:
          username: admin
          password: adminpass
          vhost: /notifications

        # наш rabbitmq.conf
        configuration: |-
          listeners.tcp.default = 5672
          management.tcp.port   = 15672
          management.tcp.ip     = 0.0.0.0
          loopback_users.guest  = false

        service:
          type: ClusterIP
          ports:
            amqp: 5672
            manager: 15672

        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: rabbitmq-dev.mycum.ru   # <-- подставь свой host
          path: /
          pathType: Prefix
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          tls: []

  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
